# Generated by Django 4.1.2 on 2023-06-03 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ges_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateurs',
        ),
        migrations.RemoveField(
            model_name='profils',
            name='code_utilisateur',
        ),
        migrations.AddField(
            model_name='profils',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='profils',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
