# Generated by Django 4.1.2 on 2023-06-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ges_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
