# Generated by Django 4.1.2 on 2023-06-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ges_auth', '0003_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
