# Generated by Django 4.1.2 on 2023-06-10 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(default='', upload_to='')),
                ('nom_doc', models.CharField(default='', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('type_doc', models.CharField(default='', max_length=50)),
                ('description_doc', models.CharField(default=' document administratif', max_length=255)),
                ('category', models.CharField(choices=[('epreuve', 'epreuve'), ('controle continu', 'controle continu'), ('session normale', 'session normale'), ('communiquer', 'communiquer'), ('emplois du temps', 'emplois du temps')], default='epreuve', max_length=30)),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ges_doc.fichier')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
