# Generated by Django 4.1.2 on 2023-06-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ges_doc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('epreuve', 'epreuve'), ('controle continu', 'controle continu'), ('session normale', 'session normale'), ('communiquer', 'communiquer'), ('emplois du temps', 'emplois du temps')], default='epreuve', max_length=30),
        ),
    ]
